name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pack Extension
        run: zip -r "osd-primary-only@mxkramb.github.io.zip" extension.js metadata.json LICENSE README.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}